CREATE DATABASE IF NOT EXISTS lista_compras_db
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lista_compras_db;

CREATE TABLE IF NOT EXISTS items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  comprado TINYINT(1) NOT NULL DEFAULT 0,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

